# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: 
    echo "installing project dependencies..."
    echo "installed react"
    echo "installed react-dom"
    echo "installed react-router-dom"
  displayName: 'Install Dependencies'

- script: |
    echo "initalising dummy database..."
    echo "adding dummy data..."
  displayName: 'Create Test Database'

- script: |
    echo "starting website building..."
  displayName: 'Build Website'

- script: |
    echo "commencing unit testing..."
  displayName: 'Run Unit Tests'

- script: |
    echo "clearing dummy database..."
  displayName: 'Remove Test Database'

- script: |
    echo "setting build version..."
  displayName: 'Set Build Version'

- script: |
    echo "sending build status notification to communication platforms"
  displayName: 'Build Succeeded'
