# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "installing project dependencies..."
    npm install
  displayName: 'Install Dependencies'

- script: |
    echo "installing project dependencies..."
    cd server
    npm install
  displayName: 'Install Backend Dependencies'

- script: |
    echo "create test database file..."
    touch main.db
    echo "populating database file from sql..."
    cd server
    node sql/sql.js
  displayName: 'Create Test Database'

- script: |
    echo "building webapp..."
    npm install
    npm run build
    cp -r server dist
    cp startserver.sh dist
    chmod 755 dist/startserver.sh
  displayName: 'Build Webapp'

- script: |
    echo "starting backend server..."
    cd server
    node server.js &
    sleep 5
    cd ..
    echo "commencing unit testing..."
    npm run test
  displayName: 'Run Unit Tests'

- script: |
    echo "sending build status notification to communication platforms"
    cd dist
    zip -r '$(Build.ArtifactStagingDirectory)'/dist.zip *
    zip -r '$(System.DefaultWorkingDirectory)'/dist.zip *
  displayName: 'Zip Build Folder'



- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(cdef35dd-a2e4-477b-9bb5-aa674344c828)'
    appType: 'webAppLinux'
    WebAppName: 'PantryTracker'
    deployToSlotOrASE: true
    ResourceGroupName: 'PantryTracker_group'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/dist.zip'
    RuntimeStack: 'NODE|22-lts'
    StartupCommand: './startserver.sh'
    DeploymentTypeLinux: 'oneDeploy'